CREATE TABLE USERLOGS (ID bigint NOT NULL, USERNAME text, "TIMESTAMP" timestamp without time zone);
CREATE TABLE USERS (ID bigint NOT NULL, USERNAME text, PASSWORD text);
CREATE TABLE ROLES (ID INT, NAME VARCHAR(20));
CREATE TABLE ENTRY_ROLES (USER_ID INT, ROLE_ID INT);
CREATE TABLE BUSINESS_ROLES (USER_ID INT, ROLE_ID INT);
CREATE TABLE TWOFA_ROLES (USER_ID INT, ROLE_ID INT);

INSERT INTO USERS (ID, USERNAME, PASSWORD) VALUES (1, 'admin', '12345');
INSERT INTO USERS (ID, USERNAME, PASSWORD) VALUES (2, 'your email', 'password');

INSERT INTO ROLES (ID, NAME) VALUES (1, 'Admin');
INSERT INTO ROLES (ID, NAME) VALUES (2, 'Manager');
INSERT INTO ROLES (ID, NAME) VALUES (3, 'User');

INSERT INTO ENTRY_ROLES (USER_ID, ROLE_ID) VALUES (1,1);
INSERT INTO BUSINESS_ROLES (USER_ID, ROLE_ID) VALUES (1,2);
INSERT INTO BUSINESS_ROLES (USER_ID, ROLE_ID) VALUES (2,2);
INSERT INTO TWOFA_ROLES (USER_ID, ROLE_ID) VALUES (2,3);